### ISSUE TITLE
todo list.

### ISSUE THREAD

**Issue by elleyer** [elleyer/Elysium#3]
### Auth
   - [ ] Async connection
     - [ ] Connection Timeout
     - [x] Requests to server
     - [x] Execute responces
   - [ ] Login action
      - [ ] Auto-login after auth
      - [x] Requests to server
      - [x] Execute responces
   - [x] Register action
      - [x] Requests to server
      - [x] Execute responces
   - [x] Guest mode
### Main menu/UI
   - [x] Animations
     - [x] Buttons animations
   - [ ] Scrolling UI list for all screens.
     - [x] Scroling using anchor positions (to the nearest side)
     - [ ] UI size by screen size (x*y)
   - [ ] Different size of elements (fix required)
   - [x] Main buttons
     - [x] Start/Styling/Scores
     - [x] Settings
   - [ ] Leaderboards(UI)
     - [ ] Fix view for different screens
   - [ ] Leaderboards(work)
     - [x] Score parsing from server
     - [ ] Limit of positions (100)
     - [ ] Clickable results => user profile
   - [ ] Performance optimization
     - [ ] Background lagging fix
     - [ ] Shader effects
     - [ ] Remove Update() in some places
   - [ ] Track Manager
     - [x] Local tracks from device
     - [ ] Downloadable tracks from server
     - [x] Playback line
     - [x] previous/next track selector
   - [ ] Player profile panel
     - [ ] Profile picture
     - [x] Nickname
     - [ ] Exp counter
     - [ ] Level
     - [x] Session nofications
     - [ ] Player statistic
      - [ ] Global ranking position
      - [ ] Total score count 
      - [ ] SpacePoint count 
### Code quality
   - [ ] Re-write slow code
   - [ ] Check a lot of scripts for optimize
### Gameplay
   - [ ] Player view
     - [x] Spaceship
   - [ ] Game/UI
     - [ ] Buttons
     - [x] Screen stick control
     - [x] Healthbar
      - [ ] HealthBox drop by random 
     - [ ] Score system
      - [ ] Score multiplier for big count of kills 
     - [x] Minimap
### Game modes
   - [ ] Multiplayer
     - [ ] Types of games
     - [ ] Server preferences
   - [ ] Offline
     - [x] Bot difficults
      - [x] Noob 
      - [x] A bit harder
      - [x] Impossible
     - [ ] Bot logic
      - [x] Death
      - [x] Targeting player
      - [ ] Ammo
      - [ ] Spawner/actions 
### Scoring system 
   - [ ] Scores
      - [ ] Points scoring
   - [ ] SpacePoints
      - [ ] Points scoring
### Weapon types
   - [x] Rocket missile
   - [x] Blaster
   - [ ] Lazer gun
     - [ ] Intantiane line from the player position
     - [x] Loop sound
### Networking
   - [ ] Statistics
     - [ ] Currently player status
     - [ ] Player statistics
      - [ ] Scores
      - [ ] Level
      - [ ] SpacePoints
   - [ ] Chat
     - [ ] Message limit
     - [ ] Auto-delete
     - [ ] Chat channels
     - [ ] Private messaging               
   - [x] Basic connection
   - [ ] Friends listing
     - [ ] List of friends
     - [ ] Requests panel
   - [ ] Rooms
     - [ ] Room managing
      - [ ] UI 
      - [ ] Rooms
      - [ ] Different players count
      - [ ] Different params for playing
      - [ ] In-room chat
   - [ ] Files
     - [ ] File server
     - [ ] Data downloading from server (music etc)
     - [ ] Avatar selector
     - [ ] Delete data from build, but download from server on first game launch
### Settings
   - [ ] Network settings
     - [ ] Connection info
      - [x] Ping 
      - [ ] Server name
     - [ ] Server choose
     - [ ] Client version
      - [ ] Update request function
   - [ ] Player settings
     - [ ] Stick Sensitivity
     - [ ] Language settings
     - [ ] Logging functions
      - [ ] Log out 
     - [ ] Private data list
     - [ ] Change password action
     - [ ] Change E-mail action
